title: "Dylan's Blog"
author: "Dylan Nakahodo"
description: "Personal Website and Blog"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: false          # show article previews on the home page instead of headlines
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: true            # enables dark mode
dark_header: true           # uses dark header whether dark_theme is enabled or not
minimal_theme: false         # radically minimalistic theme
mathjax: true

navigation:                  # show navigation links in the header
  - index.html
  - archive.md
  - categories.md
  - projects.md
  - about.md

iconfolder: "//use.fontawesome.com/releases/v5.6.3/svgs/"
icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
#  solid-envelope: ""
  brands-github: "https://github.com/dylannakahodo"
  brands-linkedin: "https://www.linkedin.com/in/dylan-nakahodo/"
  brands-twitter: "https://twitter.com/dylan_nakahodo"
#  solid-rss: ""

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
